import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Amplify } from "aws-amplify";

Amplify.configure({
  Auth: {
    identityPoolId: process.env.NEXT_PUBLIC_IDENTITY_POOL_ID,

    region: process.env.NEXT_PUBLIC_REGION,

    userPoolId: process.env.NEXT_PUBLIC_USER_POOL_ID,

    userPoolWebClientId: process.env.NEXT_PUBLIC_CLIENT_POOL_ID,

    mandatorySignIn: true,
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
